"""repo_emitter — write a complete, self-contained wrapper-agent folder into the
agent-directory repo.

Output mirrors the hand-built agents (disaster_response_agent as the reference
shape: card + server + Dockerfile + entrypoint + deps + README), plus a vendored
copy of the wrapper engine so the agent needs nothing from AgenticNetwork at
runtime. The emitted agent self-publishes via the shared ads_utils.publisher.

    agent-directory/<slug>/
      ├── <slug>.card.json     # résumé (routable: carries an oasf:<name>:<id> tag)
      ├── <slug>.py            # A2A server: endpoint_wrapper_spec + self-publish
      ├── wrapper_engine/      # vendored agent_skeleton engine (no generator/tests)
      ├── Dockerfile           # build from the agent-directory repo ROOT
      ├── entrypoint.sh        # wait for ADS, then serve
      ├── requirements.txt
      └── README.md
"""
from __future__ import annotations

import json
import os
import shutil
import stat
from pathlib import Path
from typing import Any

from .card_builder import build_card, validate_card
from .models import AgentAnswers
from .prompt_builder import build_system_prompt

# The engine package to vendor (this file lives in agent_skeleton/generator/).
ENGINE_SRC = Path(__file__).resolve().parent.parent
ENGINE_IGNORE = shutil.ignore_patterns(
    "generator", "tests", "__pycache__", "*.pyc",
    # Full-skeleton-only files (uploaded-code path + packaging); a vendored wrapper
    # engine doesn't need them, and __init__ imports base/handler_executor defensively.
    "base.py", "container_runner.py", "handler_executor.py", "pyproject.toml",
)


def _render_agent_main(answers: AgentAnswers, system_prompt: str) -> str:
    slug = answers.slug
    header = (
        '"""A2A server for a generated LLM-wrapper agent.\n\n'
        "Wraps an external, user-hosted endpoint in an LLM loop and self-publishes to\n"
        "ADS so the planner can discover it. Generated by agent_skeleton.generator;\n"
        'edit SYSTEM_PROMPT / constants below to tune behavior."""\n'
        "from __future__ import annotations\n\n"
        "import argparse\n"
        "import atexit\n"
        "from pathlib import Path\n\n"
        "from wrapper_engine.config import env_ads_addr\n"
        "from wrapper_engine.serve import create_app, load_agent_card\n"
        "from wrapper_engine.spec import endpoint_wrapper_spec\n"
        "from wrapper_engine.system_tools.call_endpoint import EndpointConfig\n\n"
        f"SLUG = {slug!r}\n"
        f"PORT = {int(answers.port)}\n"
        f"ENDPOINT_URL = {answers.endpoint_url!r}\n"
        f"PROTOCOL = {answers.protocol!r}\n"
        f"AUTH_ENV = {answers.auth_env!r}\n"
        f"MODEL = {answers.model!r}\n"
        f"CARD_PATH = Path(__file__).with_name(SLUG + '.card.json')\n"
        f"SYSTEM_PROMPT = {system_prompt!r}\n\n\n"
    )
    body = (
        "def build_spec(card):\n"
        "    endpoint = EndpointConfig(url=ENDPOINT_URL, protocol=PROTOCOL, auth_env=AUTH_ENV)\n"
        "    return endpoint_wrapper_spec(\n"
        "        name=getattr(card, 'name', SLUG),\n"
        "        endpoint=endpoint,\n"
        "        description=getattr(card, 'description', '') or '',\n"
        "        system_prompt=SYSTEM_PROMPT,\n"
        "        model=MODEL,\n"
        "    )\n\n\n"
        "def main() -> None:\n"
        "    parser = argparse.ArgumentParser(description=f'{SLUG} A2A wrapper agent')\n"
        "    sub = parser.add_subparsers(dest='command')\n"
        "    serve = sub.add_parser('serve', help='Run the A2A server and publish to ADS.')\n"
        "    serve.add_argument('--host', default='0.0.0.0')\n"
        "    serve.add_argument('--port', type=int, default=PORT)\n"
        "    serve.add_argument('--advertise-url', default=None)\n"
        "    serve.add_argument('--ads-url', default=env_ads_addr(), help='ADS server addr (defaults from env).')\n"
        "    serve.add_argument('--no-publish', action='store_true', help='Serve without ADS publish.')\n"
        "    args = parser.parse_args()\n"
        "    if args.command != 'serve':\n"
        "        parser.print_help()\n"
        "        return\n\n"
        "    import uvicorn\n\n"
        "    card = load_agent_card(CARD_PATH)\n"
        "    advertise = args.advertise_url or f'http://localhost:{args.port}/'\n"
        "    try:\n"
        "        card = card.model_copy(update={'url': advertise})\n"
        "    except Exception:\n"
        "        card.url = advertise\n\n"
        "    spec = build_spec(card)\n"
        "    app = create_app(card, model=MODEL, spec=spec)\n\n"
        "    record = None\n"
        "    if not args.no_publish:\n"
        "        from ads_utils.publisher import DirectoryPublisher, DirectoryUnavailable\n"
        "        try:\n"
        "            pub = DirectoryPublisher(server_addr=args.ads_url)\n"
        "            record = pub.publish(card, advertise_url=advertise)\n"
        "            print(f'[{SLUG}] published to ADS cid={record.backend_ref}')\n"
        "            atexit.register(lambda: pub.unpublish(record.backend_ref if record else None))\n"
        "        except DirectoryUnavailable as exc:\n"
        "            print(f'[{SLUG}] WARNING: ADS publish skipped: {exc}')\n\n"
        "    print(f'[{SLUG}] serving on {args.host}:{args.port} (url={advertise})')\n"
        "    uvicorn.run(app, host=args.host, port=args.port)\n\n\n"
        "if __name__ == '__main__':\n"
        "    main()\n"
    )
    return header + body


def _render_dockerfile(answers: AgentAnswers) -> str:
    slug = answers.slug
    return (
        f"# {answers.name} — generated LLM wrapper for an external endpoint (port {answers.port})\n"
        "# Build from the agent-directory repo ROOT:\n"
        f"#   docker build --platform linux/amd64 -f {slug}/Dockerfile -t agenticnetwork-{slug}:latest .\n"
        "FROM ghcr.io/agntcy/dir-ctl:v1.2.0 AS dirctl-src\n\n"
        "FROM python:3.12-slim\n\n"
        "RUN apt-get update && apt-get install -y --no-install-recommends curl \\\n"
        "    && rm -rf /var/lib/apt/lists/*\n\n"
        "COPY --from=dirctl-src /dirctl /usr/local/bin/dirctl\n"
        "RUN chmod +x /usr/local/bin/dirctl\n\n"
        "WORKDIR /app\n\n"
        f"COPY {slug}/requirements.txt {slug}/requirements.txt\n"
        f"RUN pip install --no-cache-dir -r {slug}/requirements.txt\n\n"
        f"COPY {slug}/ {slug}/\n"
        "COPY ads_utils/ ads_utils/\n"
        f"COPY {slug}/entrypoint.sh /entrypoint.sh\n"
        "RUN chmod +x /entrypoint.sh\n\n"
        "ENV PYTHONPATH=/app\n\n"
        f"EXPOSE {answers.port}\n\n"
        'ENTRYPOINT ["/entrypoint.sh"]\n'
    )


def _render_entrypoint(answers: AgentAnswers) -> str:
    slug = answers.slug
    env = slug.upper().replace("-", "_")
    return (
        "#!/bin/bash\n"
        "set -euo pipefail\n\n"
        'ADS_ADDR="${ADS_SERVER_ADDR:-localhost:8888}"\n'
        'ADS_HOST="${ADS_ADDR%%:*}"\n'
        'ADS_PORT="${ADS_ADDR##*:}"\n\n'
        f'echo "[{slug}] Waiting for ADS at ${{ADS_ADDR}}..."\n'
        "for i in $(seq 1 60); do\n"
        "    if python -c \"import socket; socket.create_connection(('${ADS_HOST}', ${ADS_PORT}), timeout=1).close()\" 2>/dev/null; then\n"
        f'        echo "[{slug}] ADS ready (${{i}}s)."\n'
        "        break\n"
        "    fi\n"
        '    if [ "$i" -eq 60 ]; then\n'
        f'        echo "[{slug}] ERROR: ADS not ready after 60s."\n'
        "        exit 1\n"
        "    fi\n"
        "    sleep 1\n"
        "done\n\n"
        "export PYTHONPATH=/app\n"
        f"cd /app/{slug}\n"
        f"exec python {slug}.py serve \\\n"
        f'    --host "${{{env}_A2A_HOST:-0.0.0.0}}" \\\n'
        f'    --port "${{{env}_A2A_PORT:-{answers.port}}}" \\\n'
        f'    --advertise-url "http://${{{env}_ADVERTISE_HOST:-localhost}}:${{{env}_A2A_PORT:-{answers.port}}}/"\n'
    )


def _render_requirements() -> str:
    return (
        "# Pinned to match the deployed network (ads_utils + a2a-sdk 0.3.2).\n"
        "a2a-sdk==0.3.2\n"
        "openai>=1.0\n"
        "uvicorn[standard]>=0.32.0\n"
        "httpx>=0.25.0\n"
    )


def _render_readme(answers: AgentAnswers) -> str:
    slug = answers.slug
    auth_line = (
        f"- **Auth:** reads the token from the `{answers.auth_env}` env var at call time "
        "(never stored in this repo).\n"
        if answers.auth_env
        else "- **Auth:** none configured.\n"
    )
    return (
        f"# {answers.name}\n\n"
        f"{answers.description}\n\n"
        "A **generated** LLM-wrapper agent: it fronts an external, user-hosted endpoint with "
        "an LLM loop that translates tasks into endpoint calls and normalizes the result, then "
        "publishes itself to ADS so the planner can discover it.\n\n"
        "## Endpoint\n"
        f"- **URL:** `{answers.endpoint_url}` (protocol: `{answers.protocol}`)\n"
        f"{auth_line}\n"
        "## Run locally\n"
        "```bash\n"
        f"{answers.auth_env + '=<token> ' if answers.auth_env else ''}python {slug}.py serve --no-publish --port {answers.port}\n"
        "```\n"
        "Requires `OPENAI_BASE_URL` + `OPENAI_API_KEY` (any non-empty value for vLLM) for the\n"
        "wrapper's own LLM, and `wrapper_engine` + `ads_utils` importable (PYTHONPATH=repo root).\n\n"
        "## Deploy\n"
        "Build the image from the agent-directory repo root (see the Dockerfile header). To wire it\n"
        "into the build pipeline, add the short name to `build_and_push.sh` (`AGENTS=(...)` and the\n"
        "`agent_dir()` case).\n\n"
        "> Generated by `agent_skeleton.generator`. Regenerate rather than hand-editing the\n"
        "> vendored `wrapper_engine/` so fixes propagate.\n"
    )


def emit_agent(
    answers: AgentAnswers,
    taxonomy: list[dict],
    dest_repo_root: str | Path,
    *,
    overwrite: bool = False,
) -> Path:
    """Write the full agent folder under ``dest_repo_root``; return its path."""
    answers.validate()
    slug = answers.slug
    dest = Path(dest_repo_root) / slug
    if dest.exists() and not overwrite:
        raise FileExistsError(f"{dest} already exists (pass overwrite=True to replace).")
    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True)

    # Card (validated) + baked system prompt.
    card = build_card(answers, taxonomy)
    validate_card(card)
    (dest / f"{slug}.card.json").write_text(json.dumps(card, indent=2) + "\n", encoding="utf-8")

    system_prompt = build_system_prompt(answers)
    (dest / f"{slug}.py").write_text(_render_agent_main(answers, system_prompt), encoding="utf-8")

    # Vendor the engine (no generator/tests/pycache) as `wrapper_engine`.
    shutil.copytree(ENGINE_SRC, dest / "wrapper_engine", ignore=ENGINE_IGNORE)

    (dest / "Dockerfile").write_text(_render_dockerfile(answers), encoding="utf-8")
    entry = dest / "entrypoint.sh"
    entry.write_text(_render_entrypoint(answers), encoding="utf-8")
    entry.chmod(entry.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    (dest / "requirements.txt").write_text(_render_requirements(), encoding="utf-8")
    (dest / "README.md").write_text(_render_readme(answers), encoding="utf-8")

    return dest


def emit_summary(dest: Path) -> dict[str, Any]:
    """Small manifest of what was written (for the caller/UI to report)."""
    files = sorted(str(p.relative_to(dest)) for p in dest.rglob("*") if p.is_file())
    return {"agent_dir": str(dest), "file_count": len(files), "files": files}
